### ISSUE TITLE
Nan Loss Encountered After CBL Training has Finished. Any Ideas?

### ISSUE THREAD

**Issue by marvinstanley** [mayhewsw/ner-with-partial-annotations#3]
Hello,
As the title suggests, I'm encountering this error after Finishing the CBL Training Step from main_ours.py . I've been trying to train using my own dataset using the main_ours.py script.

Here is a snippet of the log:
```
INFO:allennlp.training.trainer:Beginning training.
INFO:allennlp.training.trainer:Epoch 0/44
INFO:allennlp.training.trainer:Peak CPU memory usage MB: 2496.508
INFO:allennlp.training.trainer:GPU 0 memory usage MB: 1808
INFO:allennlp.training.trainer:Training
accuracy: 0.8291, accuracy3: 0.8524, precision-overall: 0.0147, recall-overall: 0.0080, f1-measure-overall: 0.0103, loss: 918.2449 ||:  18%|#8        | 28/155 [00:13<00:56,  2.26it/s]Traceback (most recent call last):
  File "main_ours.py", line 167, in <module>
    trainer.train()
  File "/usr/local/lib/python3.6/dist-packages/allennlp/training/trainer.py", line 480, in train
    train_metrics = self._train_epoch(epoch)
  File "/usr/local/lib/python3.6/dist-packages/allennlp/training/trainer.py", line 325, in _train_epoch
    raise ValueError("nan loss encountered")
ValueError: nan loss encountered
```

Any ideas to what might have caused this?

Thanks in advanced.

**Comment by mayhewsw** [comment]
I have heard of this happening, but I don't know what the problem is! This is very unsatisfactory, but sometimes starting with a different random seed will fix it. Please keep this thread updated if you find the underlying cause!
